name: maxi_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.25.2
  - pandas=1.5.3
  - setuptools=68.0.0
  - wheel=0.41.2
  - scikit-learn=1.1.3
  - gradio
  - pip
  - poetry

